# Site settings
title: Healthcare
email: office@michielvandewalle.com
description: Een digitaal zorgdossier voor rusthuizen met als doel om een vlottere administratie en een betere zorg te bieden
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://healtcare.michielvandewalle.com" # the base hostname & protocol for your site

# Build settings
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: pygments
github: [Repository metadata]
